### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by solarch** [interledgerjs/five-bells-demo#38]
ledger:3001 [2016-11-06T09:08:51.298Z] ERROR: ledger/7423 on Joes-MacBook-Pro.local: Parameter "url" must be a string, not undefined (module=error-handler)
ledger:3001     TypeError: Parameter "url" must be a string, not undefined
ledger:3001         at Url.parse (url.js:79:11)
ledger:3001         at Object.urlParse [as parse] (url.js:73:5)
ledger:3001         at UriManager.parse (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/five-bells-shared/lib/uri-manager.js:82:24)
ledger:3001         at Object.sendMessage (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/five-bells-ledger/src/models/messages.js:17:29)
ledger:3001         at next (native)
ledger:3001         at onFulfilled (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:65:19)
ledger:3001         at /Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:54:5
ledger:3001         at Object.co (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:50:10)
ledger:3001         at Object.toPromise (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:118:63)
ledger:3001         at next (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:99:29)
ledger:3001         at onFulfilled (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:69:7)
ledger:3001         at /Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:54:5
ledger:3001         at Object.co (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:50:10)
ledger:3001         at Object.toPromise (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:118:63)
ledger:3001         at next (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:99:29)
ledger:3001         at onFulfilled (/Users/joegaber/Dropbox/git/five-bells-demo/node_modules/co/index.js:69:7)
ledger:3001         at process._tickCallback (internal/process/next_tick.js:103:7)
ledger:3001 [2016-11-06T09:08:51.298Z] ERROR: ledger/7423 on Joes-MacBook-Pro.local: (module=error-handler)

**Comment by solarch** [comment]
I installed and started per instructions and got the above error.  What did I do wrong?  On a Mac.

**Comment by jflowers1974** [comment]
ledger:3000 [2016-11-06T20:34:36.902Z] ERROR: ledger/1365 on Jeff-Flowers-MacBook-Pro-2.local: (module=error-handler)
ledger:3000     TypeError: Parameter "url" must be a string, not undefined
ledger:3000         at Url.parse (url.js:87:11)
ledger:3000         at Object.urlParse [as parse] (url.js:81:5)
ledger:3000         at UriManager.parse (/Users/jeffflowers/interLedger2/five-bells-demo/node_modules/five-bells-shared/lib/uri-manager.js:82:24)
ledger:3000         at Object.sendMessage (/Users/jeffflowers/interLedger2/five-bells-demo/node_modules/five-bells-ledger/src/models/messages.js:17:29)

===

Same...

**Comment by emschwartz** [comment]
What version of Node.js are you two running?

**Comment by jflowers1974** [comment]
Hey there,

node 6.3.1
npm 3.10.3
Mac OS 10.10.5 (Yosemite)

thanks,

**Comment by emschwartz** [comment]
Sorry about that, please update to the latest version and it should be working again. There was a small change in the dependencies that broke the demo.

**Comment by jflowers1974** [comment]
:-)  THANK You!  Cheers.
